name: Notify Discord on Commit

on:
  push:
    branches:
      - main
      - dev

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Lấy đủ commit để tránh lỗi git log

      - name: Get Commit Messages
        id: get_commits
        run: |
          commits=$(git log -1 --pretty=format:"- \`%h\` %s by **%an**")
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Actions",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": "🚀 New Commit Pushed!",
              "description": "**Branch:** `${{ github.ref_name }}`\n**Commit Messages:**\n${{ env.commits }}",
              "color": 15258703,
              "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            }]
          }' \
          $DISCORD_WEBHOOK_URL
