name: Build & Notify Discord

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        id: build_step
        run: npm run build

      - name: Get Commit Messages
        id: get_commits
        run: |
          commits=$(git log -1 --pretty=format:"- \`%h\` %s by **%an**")
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Notify Discord (Success)
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Actions",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": "✅ Build Successful!",
              "description": "**Branch:** `${{ github.ref_name }}`\n**Commit Messages:**\n${{ env.commits }}\n\n🚀 Build completed successfully!",
              "color": 3066993
            }]
          }' \
          $DISCORD_WEBHOOK_URL

      - name: Notify Discord (Failure)
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Actions",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": "❌ Build Failed!",
              "description": "**Branch:** `${{ github.ref_name }}`\n**Commit Messages:**\n${{ env.commits }}\n\n🚨 Build failed. Check logs for details.",
              "color": 15158332
            }]
          }' \
          $DISCORD_WEBHOOK_URL
