name: Notify Discord on Commit

on:
  push:
    branches:
      - main
      - dev

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Commit Messages
        id: get_commits
        run: |
          commits=$(git log -1 --pretty=format:'- `%h` %s by **%an**')
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🔔 **New Commit Pushed!**
            **Branch:** `${{ github.ref_name }}`
            **Commit Messages:**  
            ${{ env.commits }}
            **🔗 Repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})
